language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install --upgrade -r requirements.txt
  - pip install -q -e . --use-mirrors
# command to run tests
script: python manage.py test sis
