language: python
sudo: false
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
addons:
- postgresql: "9.3"
services:
- redis-server
before_script:
- psql -c "CREATE DATABASE mydb;" -U postgres
script: 
- python manage.py test ecwsp.sis
