db:
  image: postgres
redis:
  image: redis
web:
  build: .
  command: ./run.sh
  volumes:
    - .:/code
    #- ../django-custom-field/custom_field:/usr/local/lib/python2.7/dist-packages/custom_field
    #- ../django-report-builder/report_builder:/usr/local/lib/python2.7/dist-packages/report_builder
    #- ../django-report-utils/report_utils:/usr/local/lib/python2.7/dist-packages/report_utils
    #- ../django-constance/constance:/usr/local/lib/python2.7/dist-packages/constance
    #- ../django-mass-edit/massadmin:/usr/local/lib/python2.7/dist-packages/massadmin
    #- ../django-ldap-groups/ldap_groups:/usr/local/lib/python2.7/dist-packages/ldap_groups
    #- ../django-responsive-dashboard/responsive_dashboard:/usr/local/lib/python2.7/dist-packages/responsive_dashboard
  ports:
    - "8000:8000"
  links:
    - db
    - redis
